spring.application.name=quizzer
server.port=${PORT:8080}

# using Groq instead of Gemini
spring.ai.openai.api-key=${Groq_API}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=meta-llama/llama-4-scout-17b-16e-instruct
