spring.application.name=quizzer
server.port=${PORT:8080}

spring.ai.google.genai.api-key=${API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
# spring.ai.google.genai.chat.options.model=gemma-3-1b-it
