spring.application.name=quizzer
server.port=${PORT:8080}

# using Groq instead of Gemini
spring.ai.openai.api-key=${Groq_API}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama3-8b-8192
